# sls cloud organizstion target
org: hei
# sls cloud app name
app: payment-gateway-be-saas-app
# sls cloud service prefix name
service: payment-gateway-be
# default deployment to singapore
region: ap-southeast-1
# default deployment aws profile set to
profile: hei